spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=mini_dish_db_manager
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

